source1:
  name: source1
  url: https://source1.com/v1/api

source2:
  name: source2
  url: https://source2.com/v2/api


feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
